version: '3'
volumes:
  dbdata:
services:
  workaround-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=movie-demo
      - MYSQL_ROOT_PASSWORD=apppassword
    ports:
      - 3308:3306
    volumes:
      - dbdata:/var/lib/mysql
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - workaround-mysql
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    environment: 
      - spring.datasource.url=jdbc:mysql://workaround-mysql:3306/movie-demo
      - spring.datasource.username=root
      - spring.datasource.password=apppassword
